### ISSUE TITLE
Discussion : Multiple path LogicalUnit implementation

### ISSUE THREAD

**Issue by CallisteH** [ManageIQ/manageiq-providers-ibm_power_hmc#43]
From the HMC we have the possibility to have a VirtualSCSIStorage instance reachable from several paths, as suggested by the scheme defined by @dberg1.

Today in ManageIQ we try to implement VirtualSCSIStorage in the disks table. We are thinking about the best approach to inventory VirtualSCSIStorage, and more precisely, in this case, LogicalUnit (HMC object). 

![image](https://user-images.githubusercontent.com/70648532/155560198-314b7ba4-9586-4cb7-aae7-3e697c0ce886.png)

**Comment by CallisteH** [comment]
Following a conversation with @Fryguy @agrare and @jaywcarman, the possibility of seeing the `volume_mapping` table was brought up.

Is there an existing provider that would do a similar job?

**Comment by agrare** [comment]
So @CallisteH I think I need a little more clarity about this diagram, both LPARs and VIOSs are VMs so do some VMs connect to an MPIO through other VMs?  It looks like the two VIOs' vscsi adapters are connected to the LPAR vscsi adapter which is then connected to the MPIO

**Comment by dberg1** [comment]
VIOSes are special VMs that have direct disk access and serve disk I/Os to other VMs (LPARs).
LPARs access disks through the VIOSes.

**Comment by agrare** [comment]
Oh okay interesting, would it be safe to say that a VIOS disk backing is an LPAR disk?

**Comment by agrare** [comment]
We could use the `GuestDevice` model which is what we use to track a VM's virtual hardware, currently they track NICs but could easily be extended to track vSCSI controllers.  I've wanted to track virtual storage controllers on vmware for a while so this seems like a good time to do that.

**Comment by CallisteH** [comment]
To simplify, I would say that in the HMC there is a relationship LPAR <--OneToMany--> VIOS <--ManyToOne--> LogicalUnit (through VSCSI Mappings).
On MIQ, both VIOSes and LPARs are in the `vm` table. This `vm` table has a OneToMany relationship with `hardwares`. I think we may have a problem in the relationship between VM and Hardware (OneToOne) for the specific case of the HMC. If we consider a concrete case of multipath where we have LPAR 1 linked to two vioses (VIOS1 and VIOS2) which are linked to a single LUN logical unit, as the diagram below suggests:
**Diagram of a storage infrastructure with multipath**
![Diagram of a storage infrastructure with multipath](https://user-images.githubusercontent.com/70648532/162776762-80d98955-a463-4e88-9e40-c92d178ef194.png)

The `hardwares` table is necessarily linked to a single `vm` because the model entity is defined as vm <--OneToOne--> hardwares.
So I think we can't have the same instance of `disks` or `guest_devices` linked to several vms, we will necessarily have to create a copy. Except misunderstanding?

**Entity-relationship diagram from MIQ**
![Entity-relationship diagram from MIQ](https://user-images.githubusercontent.com/70648532/162779522-5a0ed73e-1fa4-486e-a797-f41960bb7e15.png)

**Comment by agrare** [comment]
Guest devices have a `parent_device_id` that would let you track the multipath relationships, so a disk backing could have one "MPIO" guest device, which would have multiple child guest devices for each IO path, or if you are able to use miq_scsi_targets that can also belong to a guest_device so you could have multiple of those belonging to a single MPIO guest_device.

You can then put the MPIO guest_device as the disk.backing

**Comment by CallisteH** [comment]
Thanks for your comment; 

May be this schema 
![Diagram of a storage infrastructure with multipath](https://user-images.githubusercontent.com/70648532/164240117-c4a768ff-aaa0-4269-9f39-cf754875bbdf.png)

Could be approximately designed in the MIQ model as following ? 
![Representation of a logical unit with two I/O paths](https://user-images.githubusercontent.com/70648532/164240230-5cd3f8a4-231b-4166-819f-41bf43ff0994.png)

**Comment by CallisteH** [comment]
Fixed by https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/91
