### ISSUE TITLE
[Najdorf] IBM Power HMC Enhancements

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-ibm_power_hmc#8]
- [x] Expand inventory collection
  - [x] Virtual Switches - https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/17
  - [x] Networks - https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/17
  - [x] Ethernet Adapters - https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/18
  - [x] Templates - https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/22
  - [x] Logical Ports - https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/23
  - [x] Storages - https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/31
- [x] Event handler - https://github.com/ManageIQ/manageiq-content/pull/692
- [x] Provision
  - [x] Vm to Template https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/26

**Comment by jaywcarman** [comment]
Deferring metrics collection to a subsequent release.
